// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VLU_API.Data;

namespace VLU_API.Migrations
{
    [DbContext(typeof(VLUcontext))]
    partial class VLUcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VLU_API.Models.CurriculumVitae", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageAvatar")
                        .HasColumnType("nvarchar");

                    b.Property<string>("Introduce")
                        .HasColumnType("nvarchar");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("CurriculumVitaes");
                });
#pragma warning restore 612, 618
        }
    }
}
